version: '3.8'
services:
  novelcraft-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: novelcraft-prod
    ports:
      - "8020:80"
    restart: unless-stopped
    networks:
      - novelcraft-net
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: writingapptunnel
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    volumes:
      - ./writingApptunnel:/etc/cloudflared
    restart: unless-stopped
    networks:
      - novelcraft-net
networks:
  novelcraft-net:
    driver: bridge
